version: "3.4"
services:
  backend:
    container_name: backend
    hostname: backend
    image: domppolak/aws-ttt-backend
    networks:
      - priv-network
    ports:
      - "8080:8080"

  frontend:
    container_name: frontend
    hostname: frontend
    image: domppolak/aws-ttt-frontend
    networks:
      - priv-network
    ports:
      - "4200:80"
    environment:
      - BASE_URL:
      - BASE_WEBSOCKET: 

networks:
  priv-network:
    driver: bridge
