version: "3.4"
services:
  backend:
    container_name: backend
    hostname: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: backend
    ports:
      - "8080:8080"
    env_file: .env

  frontend:
    container_name: frontend
    hostname: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: frontend
    ports:
      - "4200:80"
    env_file: .env
