version: "3.4"
services:
  backend:
    container_name: backend
    hostname: backend
    image: "domppolak/aws-ttt-backend"
    ports:
      - "8080:8080"
    networks:
      - my-network

  frontend:
    container_name: frontend
    hostname: frontend
    image: "domppolak/aws-ttt-frontend"
    ports:
      - "80:80"
    networks:
      - my-network
    environment:
      - BASE_URL=
      - BASE_WEBSOCKET=

networks:
  my-network:
    driver: bridge

